---
apiVersion: v1
kind: Service
metadata:
  name: frigate 
spec:
  type: NodePort 
  selector:
    app: frigate 
  ports: 
  - name: "tcp-port" 
    port: 5050 
    targetPort: 5000
  - name: "rtsp-port"
    port: 8554
    targetPort: 8554
  - name: "webrtc-tcp-port"
    port: 8555
    targetPort: 8555
    protocol: TCP
  - name: "webrtc-udp-port"
    port: 8555
    targetPort: 8555
    protocol: UDP
  externalIPs:
  - 192.168.0.211
  - 192.168.0.221
  - 192.168.0.222
  - 192.168.5.223
  - 192.168.0.224
