---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frigate-deployment.yaml
  - frigate-svc.yaml
secretGenerator:
  - name: frigate-password 
    files:
      - FRIGATE_RTSP_PASSWORD=./secrets/password.txt
generatorOptions:
  disableNameSuffixHash: true

